# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mean_upper <- function(sp) {
    .Call('Refficiency_mean_upper', PACKAGE = 'Refficiency', sp)
}

Refficiency <- function(g) {
    library(igraph)
    sp <- shortest.paths(g)
    E <- mean_upper(sp)
    return(E)
}

